### ISSUE TITLE
movement system on straight line

### ISSUE THREAD

**Issue by PonomarevDA** [PonomarevDA/MobileRobotControlSystem#10]

**Comment by PonomarevDA** [comment]
This module is described in [robot_control.c](https://github.com/PonomarevDA/MobileRobotControlSystem/blob/master/robot_control.c).
The main function is [move_forward(uint16_t distance)](https://github.com/PonomarevDA/MobileRobotControlSystem/blob/5bb5e07fbdc7fad3b8aacea333e1bb1810f5f31a/robot_control.c#L438-L514).

At this moment robot can only correct move forward.
1. Passive and Active check for an obstacle is n't implemented because rangefinder.
2. P-regulator need some test and calibration.
3. Smooth change speed is in process. Acceleratin is work well, but i have problem in deceleration.

After I fix above problem, I will close this issue and add new comment.

**Comment by KaiL4eK** [comment]
Maybe, it is better to add I-part to your regulation? It can give the robot capability to stop one wheel if another one is stopped.

**Comment by PonomarevDA** [comment]
Of corse :)
I did it: [PI-regulator function](https://github.com/PonomarevDA/MobileRobotControlSystem/blob/96e7159d29f74d2a5c89f7a5685a7731172b23cb/robot_control.c#L391-L423).
Also i tested this function in mini-programm "pulse encoder simulation":
![image](https://user-images.githubusercontent.com/36133264/40514950-a88640d4-5fb3-11e8-92de-25bc74a0436d.png)
In theory, this system must have capability to stop one wheel if another one is stopped.
Tomorrow i am going to test it.

**Comment by PonomarevDA** [comment]
PI-regulator is work like theory.

**Comment by KaiL4eK** [comment]
Nice work, issue is still actual?
