### ISSUE TITLE
[common] filename of rangefinder

### ISSUE THREAD

**Issue by KaiL4eK** [PonomarevDA/MobileRobotControlSystem#12]
https://github.com/PonomarevDA/MobileRobotControlSystem/blob/3612d45584b70736cf1becc1364dc87d094d6619/ranghefinder.c#L2
The name in comment is ok, but source filename has mistake)

**Comment by PonomarevDA** [comment]
I created new project :)
Fixed.

**Comment by KaiL4eK** [comment]
Critical, but nice fix =)
