### ISSUE TITLE
[rangefinder] interrupt data processing overflow

### ISSUE THREAD

**Issue by KaiL4eK** [PonomarevDA/MobileRobotControlSystem#13]
https://github.com/PonomarevDA/MobileRobotControlSystem/blob/3612d45584b70736cf1becc1364dc87d094d6619/ranghefinder.c#L76
Is it processing the timer overflow? How often it can happen?

**Comment by PonomarevDA** [comment]
It is aboat how often TMR89:
https://github.com/PonomarevDA/MobileRobotControlSystem/blob/3612d45584b70736cf1becc1364dc87d094d6619/hard.c#L139-L145

**Comment by KaiL4eK** [comment]
Oh, one error per 36 minute is good for now =)
